from code.util.colors import Colors as C


class Colors:
    FRAME_TOP = C.DARK_GRAY
    FRAME_BOTTOM = C.WHITE
    BACKGROUND = C.BLACK
    STANDARD_BACKGROUND = C.BLACK
    STANDARD_LINE = C.WHITE
    STANDARD_PLATFORM = C.DARK_RED
    STANDARD_FENCE = C.GREEN
    