from code.util.colors import Colors as C


class Colors:
    MENU_BACKGROUND = C.LIGHT_GRAY
    BUTTON_BACKGROUND = C.LIGHT_GRAY
    BUTTON_FRAME_TOP = C.WHITE
    BUTTON_FRAME_BOTTOM = C.DARK_GRAY
    BUTTON_FRAME_TOP_PRESSED = C.DARK_GRAY
    BUTTON_FRAME_BOTTOM_PRESSED = C.LIGHT_GRAY
    BUTTON_BACKGROUND_PRESSED = C.LIGHT_GRAY
    BUTTON_BACKGROUND_OVER = C.LIGHT_BLUE
    BUTTON_TEXT = C.BLACK
    LIST_BACKGROUND = BUTTON_BACKGROUND
    LIST_BACKGROUND_OVER = BUTTON_BACKGROUND_OVER
    LIST_FRAME_TOP = C.DARK_GRAY
    LIST_FRAME_BOTTOM = C.DARK_GRAY
    LIST_TEXT = C.BLACK
    