from code.util.colors import Colors as C


class Colors:
    BACKGROUND = C.LIGHT_GRAY
    TOPLINE = C.LIGHT_BLUE
    TITLE = C.BLACK
    FRAME_TOP = C.WHITE
    FRAME_BOTTOM = C.DARK_GRAY
    BUTTON_BACKGROUND = C.LIGHT_GRAY
    BUTTON_BACKGROUND_PRESSED = C.LIGHT_GRAY
    BUTTON_FRAME_TOP = C.WHITE
    BUTTON_FRAME_BOTTOM = C.DARK_GRAY
    BUTTON_FRAME_TOP_PRESSED = C.DARK_GRAY
    BUTTON_FRAME_BOTTOM_PRESSED = C.LIGHT_GRAY
    BUTTON_TEXT = C.BLACK
    
    
class AskColors:
    QUESTION = C.BLACK
    
    
class FileColors:
    TEXTBOX_FRAME_TOP = C.DARK_GRAY
    TEXTBOX_FRAME_BOTTOM = C.WHITE
    